//
// Created by Michael Hirsch on 04.02.26.
//

#pragma once

enum class SpriteID {

    //NONE,
    PLAYER_SHIP_MIDDLE,
    PLAYER_SHIP_LEFT,
    PLAYER_SHIP_RIGHT,
    YELLOW_ENEMY_0,
    YELLOW_ENEMY_1,
    RED_ENEMY_0,
    RED_ENEMY_1,
    BLACK_ENEMY_0,
    BLACK_ENEMY_1,
    BASE_PLAYER_PROJECTILE,
    BASE_ENEMY_PROJECTILE,
    ARROW_LEVEL_UP,
    SHIELD_ICON,
    SHIELD_EFFECT,
    SHIELD_UI,
    SPLIT_SHOT,
    GLAIVE,
    ROCKET,
    ARROW,
    EXPLOSION,
    RANDOM_PROJECTILE,
    COUNT
};